name: Gitea Test
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [ push ]

jobs:
  test-job:
    name: Python test job
    runs-on: ubuntu-22.04
    timeout-minutes: 60
    steps:
      - name: Update to recent tool version
        shell: bash
        run: |
          apt-get update
          apt-get install -y nodejs git curl wget
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install poetry
        run: pip3 install poetry
      - name: Install dependencies
        run: poetry install
      - name: Run tests
        run: poetry run pytest -v
