name: Gitea Test
run-name: ${{ gitea.actor }} is testing out Gitea Actions 🚀
on: [push]

jobs:
  test-job:
    name: Python test job
    runs-on: ubuntu-22.04
    steps:
      - name: Update to recent tool version
        shell: bash
        run: |
            apt-get update
            apt-get install -y nodejs
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
           python-version: '3.11.6' 
      - name: Display Python version
        run: python3 -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: pip3 install -r requirements.txt        
      - name: Run tests
        run: pytest --no-header -v --junit-xml results.xml
